Algoritmo "MenorMaior"

Var
a,b,op:inteiro


Inicio
escreval("digite o 1º numero")
leia(a)
escreval("digite o 2º numero")
leia(b)

se (a>b)entao
escreval("o maior numero e: ",a)
senao
escreval("o maior numero e: ",b)
fimse

  escreval ("digite 1 para somar os numeros")
  escreval ("digite 2 para mutiplicar os numeros")
  escreval ("digite 3 para subtrair os numeros")
  escreval ("digite 4 para dividir os numeros")
  
  escreva("digite aqui: ")
  leia(op)
  

escolha(op)
caso 1
escreval("a soma e: ",a+b)
caso 2
escreval("a multiplicacao e: ",a*b)
caso 3
escreval (" a subtracao e: ",a-b)
caso 4
escreval("a divisao e: ",a/b)
fimescolha


     

Fimalgoritmo
