Algoritmo "dardo"

Var

a, b, c : real


Inicio

escreval("digite o valor do primeiro dardo")
leia(a)
escreval("digite o valor do segundo dardo")
leia(b)
escreval("digite o valor do terceiro dardo")
leia(C)

se (a>c) e (a>b) entao
escreval(" o dardo que mais pontuou foi: ",a)
fimse

se (b>a) e (b>c) entao
escreval( "o dardo que mais pontuou foi:",b)
fimse

se(c>a) e (c>b) entao
escreval ( "o dardo que mais pontuou foi:",c)
fimse


Fimalgoritmo