Algoritmo "idades"
var
idade1, idade2:real
 nome1, nome2:caractere
 soma:real
 divisao:real
 
 inicio
 escreva("insira o nome da 1° pessoa")
 leia(nome1)
 escreval("agora a idade")
 leia(idade1)
 escreval("insira o nome da 2° pessoa")
 leia(nome2)
 escreval("agora a idade")
 leia(idade2)
 
 soma<- idade1+idade2
 divisao<- soma/2
 
 escreval("a idade media de",nome1 "e",nome2 "é igual a:",divisao)
 
 

Fimalgoritmo