Algoritmo "semnome"
var
a,b,c:inteiro

Inicio
escreval("insira o primeiro numero")
leia(a)
escreval("insira o segundo numero")
leia(b)
escreval("insira o terceiro numero")
leia(c)

se (a<b)e(a<c)entao
escreval("o menor numero é ",b)
senao
se (b<a)e(b<c) entao
escreval("o menor numero é ",b)
senao
se (c<a)e(c<b) entao
escreval(" o menor numero é",c)
 fimse
   fimse
     fimse



Fimalgoritmo